### PR TITLE
Support for bluetooth controllers

### PR DESCRIPTION
**Pull request by LeifMessinger**
My implementation is a bit sketchy.
Not sure if I should have used `HidD_GetInputReport `or `HidD_GetFeature`, but I ran it through the debugger and it got my inputs.

### CODE REVIEW

**Comment by LeifMessinger** [comment]
I realized that the keepRunning loop doesn't loop a first time, that can be fixed by making keepRunning true at first, then setting it to false after SUCCESS.

**Comment by Ohjurot** [comment]
Thanks for your participation! However just using `HidD_GetInputReport` via Bluetooth does not do the trick. The problem is that the format of the input report using Bluetooth is different. The format using Bluetooth is as follows: 
0x01 : LStick X
0x02 : LStick Y 
0x03 : RStick X
0x04 : RStick Y 
0x05 : DPad and PS5 Buttons
0x06 : Bumpers, Triggers digital state, sticks, share and menu button
0x07 : Package number
0x08 : Left Trigger
0x09 : Right Trigger
while the USB format is a bit different in layout and has more features (Touch, accelerometer, gyroscope). Probably due to power saving... I suspect you need to send a specific pair of values to the controller to enable / retrieve these addition parameters. 
I already found a [trace](https://github.com/darthcloud/bt_traces/blob/master/blueretro_logs/blueretro_v0.7_ps5_dualsense_page.txt) of a Bluetooth communication. I will get to that as soon as I am done with the USB protocol. 
I will still merge your pull request, but I will split the evaluation of the input buffer readings according to the controller’s connection type.
If you are interested: I have attached you my notes on the DualSense USB protocol, so you can play around and see If you get something more to work. 
[ps_controler.txt](https://github.com/Ohjurot/DualSense-Windows/files/5541602/ps_controler.txt)
(Also note the big HID Output report size of 547 Bytes while using Bluetooth... That will be a pain for sure... Still hoping this is a typo in the HID descriptor…)

Now to `HidD_SetFeature`: I am also a bit confused on when to use what. I did not look at the feature report of the DualSense controller yet. But I neither had any luck with it in the past (May also be the case because the XBOX controller is quite a bit*h if it comes to HID compatibility....). If you want, you can try to read and write to it and see If it makes any changes.

**Comment by Ohjurot** [comment]
Ah I forgot to mention that I may also change the allocation of the report buffer to user supplied allocation functions in the future. This should enable the user to use their own custom allocators. But I am currently not quite sure on how I will do this exactly.

**Comment by LeifMessinger** [comment]
I made a button detector for bluetooth, pushed it to https://github.com/LeifMessinger/DualSense-Windows/tree/bluetooth
It seems like the touchpad and gyro features don't even register.

**Comment by Ohjurot** [comment]
I will look at Programm output later when I’m back at home on my computer. But so far I think that our experience is nearly the same: On Bluetooth some values are not coming in. I think that the PlayStation / Computer needs to explicitly ask the controller for sending this data. There seems to be an issue on the DS4Windows project discussing that controller as well. I will check it out later maybe they already accomplished that.

**Comment by Ohjurot** [comment]
@LeifMessinger I have looked at the output of your program. It really looks like the additional buttons and data are not being sent by default via Bluetooth. If you check out my main branch you will find my integration of Bluetooth as it currently is. At the moment I’m working on the adaptive triggers via USB. I will come back to Bluetooth as soon as I can. I have changed my plan to include a basic Bluetooth support within the first release planned for next week.

**Pull request merged**
